version: "3.8"

services:
  web:
    container_name: graphql-java
    hostname: graphql-java
    image: graphql-java
    stdin_open: true
    tty: true
    build:
      context: .
      dockerfile: Dockerfile
      args:
        END: 'TEST'
    volumes:
      - "/tmp:/tmp"

    ports:
      - '8080:8080'

    restart: 'on-failure'

    depends_on:
      - db

    logging:
      driver: fluentd
      options:
        fluentd-address: "localhost:24224"
        fluentd-async-connect: "true"
        tag: 'web-containerssh.{{.ID}}'

    environment:
      - SLEEP_LENGTH=5
      - spring.datasource.url=jdbc:mysql://db:3306/graphql-java?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false&autoReconnect=true&allowPublicKeyRetrieval=true&createDatabaseIfNotExist=true
      - spring.datasource.username=test
      - spring.datasource.password=root1234
      - spring.kafka.bootstrap-servers=kafka:9092
      - spring.security.oauth2.client.registration.graphql-java.client-id=graphql-java
      - spring.security.oauth2.client.registration.graphql-java.authorization-grant-type=authorization_code
      - spring.security.oauth2.client.registration.graphql-java.scope=openid, profile, roles
      - spring.security.oauth2.client.provider.graphql-java.issuer-uri=http://localhost:8180/realms/graphql-java
      - spring.security.oauth2.client.provider.graphql-java.user-name-attribute=test
      - spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8180/realms/graphql-java
      - spring.security.oauth2.client.registration.graphql-java.client-secret=ABgvt5rZ96furvxhTWTQPPXWh03l4ymF
      - spring.security.oauth2.client.registration.graphql-java.redirect-uri=http://localhost:8080/login/oauth2/code/graphql-java
      - service.module=web
      - AWS_REGION=ap-south-1
      - AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY
      - AWS_ENDPOINT_URL=http://localhost:4566
      - AWS_ENDPOINT_URL_SNS=http://localhost:4566
      - OPENAI_API_KEY=$OPENAI_API_KEY
      - NEWRELIC_API_KEY=$NEWRELIC_API_KEY
  db:
    image: 'mysql:latest'
    container_name: db
    command: --slow-query-log=on --slow-query-log-file=/var/log/mysql/slow.log
    environment:
      - 'MYSQL_DATABASE=graphql-java'
      - 'MYSQL_PASSWORD=root1234'
      - 'MYSQL_ROOT_PASSWORD=root1234'
      - 'MYSQL_USER=test'
    ports:
      - '3306:3306'